services:  
  db:
    image: mysql:8.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: to_do_list
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - toDoList-network
  to-do-list:
    image: cadenassi/to-do-list
    restart: always
    build: .
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/to_do_list?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - toDoList-network
networks:
  toDoList-network:
    driver: bridge