cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://cadenassi.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/to_do_list?useTimezone=true&serverTimezone=UTC
    username: root
    password: walo1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
springdoc:
  pathsToMatch: /tasks/v1/**
  swagger-ui:
    use-root-path: true